### ISSUE TITLE
Ffmpeg

### ISSUE THREAD

**Issue by kripper** [Breta01/android-linux-scripts#34]
Hi @Breta01 

Did you have success with ffmpeg?

**Comment by Breta01** [comment]
Hi,
Tbh I haven't worked with this in a long time. I remember that there were some issues when I tried to build with ffmpeg and you needed to install some additional libraries. But maybe now the support is better, and it will be possible without an issue. You can also try installing `pip install opencv-python` directly. The scripts here are bit outdated.

**Comment by kripper** [comment]
Right. I installed opencv and ffmpeg packages without any problem. Thanks.
